quranic-universal-library-main/config/routes.rb
Rails.application.routes.draw do
  # Redirect old admin paths to new CMS paths
  get '/admin', to: redirect('/cms', status: 301)
  get '/admin/*path', to: redirect(status: 301) { |params, _req| "/cms/#{params[:path]}" }

  ActiveAdmin.routes(self)

  root to: 'landing#home'

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :chapters, only: [:index, :show] do
        member do
          get 'verses', to: 'verses#index', filter: 'by_chapter'
        end
      end

      namespace :audio do
        get 'surah_recitations', to: 'recitations#surah_recitations'
        get 'surah_recitations/:id', to: 'recitations#surah_recitation_detail'
        get 'surah_recitations/:id/wav_manifest', to: 'recitations#wav_manifest'

        get 'ayah_recitations', to: 'recitations#ayah_recitations'
        get 'ayah_recitations/:id', to: 'recitations#ayah_recitation_detail'

        get 'surah_segments/:recitation_id', to: 'segments#surah_segments'
        get 'ayah_segments/:recitation_id', to: 'segments#ayah_segments'
      end

      get '/verses/select2', to: 'verses#select2'
    end
  end

  get 'tools', to: 'community#tools', as: :tools
  get '/ayah-boundaries', to: 'community#ayah_boundaries', as: :ayah_boundaries
  get 'docs/:key', to: 'community#docs', as: :docs
  get 'tools/help/:key', to: 'community#tool_help', as: :tools_help
  get 'community/chars_info', as: :chars_info
  get 'svg', to: 'community#svg_optimizer'
  get 'credits', to: 'community#credits', as: :credits
  get 'faq', to: 'community#faq', as: :faq
  get '/compare_ayah', to: 'verses#compare', as: :compare_ayah
  
  get 'arabic_transliterations/:surah_number/export', to: "arabic_transliterations#render_surah"
  get 'foot_notes/:id', to: "foot_notes#show"

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  authenticated :user, ->(user) { user.is_super_admin? || user.is_admin? } do
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :tajweed_words, except: [:new, :destroy]
  get 'tajweed_rule/:rule', to: 'tajweed_words#rule_doc', as: :tajweed_rule

  resources :morphology_phrases do
    member do
      get :phrase_verses
    end
  end

  namespace :morphology do
    get 'roots/:id', to: 'roots#show', as: :root
    get 'lemmas/:id', to: 'lemmas#show', as: :lemma
    get 'stems/:id', to: 'stems#show', as: :stem
  end

  resources :user_projects, except: [:index, :destroy]
  resources :resources do
    get '/:token/download', action: 'download' , as: :download_file

    member do
      get :copyright
    end

    collection do
      get '/:type/:id', action: 'detail', as: :detail
      get '/:type/:id/related_resources', action: 'related_resources', as: :related
    end
  end

  resources :ayah_audio_files do
    member do
      get :segment_builder
      get :segments
      post :save_segments
    end
  end

  resources :surah_audio_files do
    member do
      get :segment_builder
      get :segments
      post :save_segments
    end

    collection do
      get :builder_help
    end
  end

  resources :mushaf_layouts, except: [:delete, :new] do
    member do
      put :save_page_mapping
      put :save_line_alignment
    end
  end

  resources :word_concordance_labels, only: [:show, :index] do
    member do
      get :word_detail
      get :segment_detail
      put :update_segment
    end
  end

  resources :learning_activities, only: [:show, :index]
  resources :arabic_transliterations, except: :delete
  resources :word_text_proofreadings, only: [:index, :show] do
    collection do
      get :compare_words
    end
  end
  resources :translation_proofreadings, except: :delete
  resources :tafsir_proofreadings, except: :delete
  resources :word_translations, except: :delete do
    member do
      match :group_info, via: [:get, :post]
    end
  end
  resources :surah_infos, except: :delete do
    member do
      get :history
      get :changes
    end
  end
  resources :translation_diffs, only: [:index, :show]

  namespace :exports do
    get :word
    get :ayah
    get :mushaf_page
    get :mushaf
  end

  namespace :segments do
    get '/', to: 'dashboard#show', as: :dashboard
    get '/failures', to: 'dashboard#failures', as: :failures
    get '/word_failures', to: 'dashboard#word_failures', as: :word_failures
    get '/word_failure_detail', to: 'dashboard#word_failure_detail', as: :word_failure_detail
    get '/detections', to: 'dashboard#detections', as: :detections
    get '/logs', to: 'dashboard#logs', as: :logs
    get '/reciters', to: 'dashboard#reciters', as: :reciters
    get '/reciters/:id', to: 'dashboard#reciter', as: :reciter
    get '/timeline', to: 'dashboard#timeline', as: :timeline
    get '/ayah_report', to: 'dashboard#ayah_report', as: :ayah_report
    get '/review_ayahs', to: 'dashboard#review_ayahs', as: :review_ayahs
    post '/reciters/:id/download', to: 'dashboard#download_reciter', as: :download_reciter
    match '/setup_db', to: 'dashboard#setup_db', via: [:get, :post], as: :setup_db
  end

  get '/ayah/:key', to: 'ayah#show', as: :ayah
  match '/404', to: 'application#not_found', via: :all
  #  match '*unmatched', to: 'application#not_found', via: :all
end

quranic-universal-library-main/app/controllers/translation_proofreadings_controller.rb
class TranslationProofreadingsController < CommunityController
  before_action :find_resource
  before_action :authenticate_user!, only: %i[edit update]
  before_action :authorize_access!, only: %i[edit update]

  def show
    #TODO: use presenter to load the translation
    @translation = Translation
                     .includes(:verse, :foot_notes)
                     .where(resource_content_id: @resource.id)
                     .find_by_verse_id(params[:id])

    if @translation.blank?
      return redirect_to translation_proofreading_path(resource_id: @resource.id), alert: "Sorry translation not found for this ayah."
    end
  end

  def edit
    @translation = Translation
                     .includes(:verse, :foot_notes)
                     .where(resource_content_id: @resource.id)
                     .find_by_verse_id(params[:id])

    if @translation.blank?
      return redirect_to translation_proofreading_path(resource_id: @resource.id), alert: "Translation not found"
    end
    @draft_translation = @translation.build_draft
  end

  def update
    @translation = Translation
                     .where(resource_content_id: @resource.id)
                     .find_by_verse_id(params[:id])

    if @translation.save_suggestions(translation_params, current_user)
      redirect_to translation_proofreading_path(@translation.verse.id, resource_id: @resource.id),
                  notice: 'Your suggestions are saved successfully'
    else
      render action: :edit, alert: @translation.errors.full_messages
    end
  end

  def index
    @ayah_translations = ResourceContent.translations.one_verse
    translations = Translation.includes(:verse, :foot_notes).where(resource_content_id: @resource.id)

    if params[:filter_chapter].to_i > 0
      translations = translations.where("verses.chapter_id": params[:filter_chapter].to_i)
    end

    if params[:verse_number].to_i > 0
      translations = translations.where("verses.verse_number": params[:verse_number].to_i)
    end

    if params[:query].present?
      translations = translations.text_search(params[:query])
    end

    order = if params[:sort_order] && params[:sort_order] == 'desc'
              'desc'
            else
              'asc'
            end

    @pagy, @translations = pagy(translations.order("verses.verse_index #{order}"))
  end

  protected

  def translation_params
    params.require(:draft_translation).permit(
      :draft_text,
      foot_notes_attributes: %i[
        id
        _destroy
        draft_text
        foot_note_id
      ]
    )
  end

  def find_resource
    return @resource if @resource

    params[:resource_id] ||= 131
    @resource = ResourceContent.find(params[:resource_id])
    @presenter.set_resource(@resource)
  end

  def load_resource_access
    @access = can_manage?(find_resource)
  end

  def init_presenter
    @presenter = TranslationPresenter.new(self)
  end
end

quranic-universal-library-main/app/views/translation_proofreadings/_ayah_view.html.erb
<h2>Translation for <%= verse.verse_key %></h2>

<div class="qpc-hafs my-3">
  <%= verse.text_qpc_hafs %>
</div>

<div id="ayah_text" style="font-size: 30px; margin-top: 10px"
     class="<%= @translation.language_name %>"
     data-controller="translation-footnote"
>
  <%= safe_html @translation.text %>
</div>

<% if @translation.foot_notes.present? %>
  <div class="mt-3 mt-md-5">
    <h2>Foot notes</h2>
    <% @translation.foot_notes.each do |foot_note| %>
      <div style="font-size: 30px;margin-top: 10px">
        <strong><%= foot_note.id %></strong>
        <div class="<%= @translation.language_name %>">
          <%= safe_html foot_note.text %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

quranic-universal-library-main/app/views/translation_proofreadings/_page_view.html.erb
<%
  translations = Translation.where(
    resource_content_id: @resource.id,
    page_number: verse.page_number
  ).order('verse_id ASC')
%>

<div class="page-wrapper container-lg">
  <div class="d-flex justify-content-center">
    <div>
      <% translations.each do |ayah_translation| %>
        <div class="p-2">
          <%= safe_html ayah_translation.text %>
          <span class="border bg-primary">
            <%= ayah_translation.verse_key %>
          </span>
        </div>
      <% end %>
    </div>
  </div>
</div>

quranic-universal-library-main/app/views/translation_proofreadings/_page_with_arabic_view.html.erb
<%
  translations = Translation.where(
    resource_content_id: @resource.id,
    page_number: verse.page_number
  ).order('verse_id ASC')
%>

<div class="page-wrapper container-lg">
  <div class="d-flex justify-content-center">
    <div>
      <% translations.each do |ayah_translation| %>
        <div class="p-2">
          <div class="qpc-hafs">
            <%= ayah_translation.verse.text_qpc_hafs %>
          </div>

          <div class="my-2">
            <%= safe_html ayah_translation.text %>
            <span class="border bg-primary">
            <%= ayah_translation.verse_key %>
          </span>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

quranic-universal-library-main/app/views/translation_proofreadings/_page_with_pdf_view.html.erb
<div class="page-wrapper container-lg">
  <%= render SplitScreenComponent.new do |component| %>
    <%= component.with_left do %>
      <%= render 'shared/pdf_or_archive_embed' %>
    <% end %>
    <%= component.with_right do %>
      <%= render 'page_view', verse: verse %>
    <% end %>
  <% end %>
</div>

quranic-universal-library-main/app/views/translation_proofreadings/edit.html.erb
<%= render 'tools/header',
           name: "Ayah translation",
           title: "Update #{@resource.name} translation for #{@translation.verse.verse_key}",
           key: 'ayah_translation'
%>

<% lang = @resource.language_name.to_s.downcase %>

<%= render 'shared/access_message' %>

<div class="page-wrapper container-lg">
  <div class="page-section">
    <%= form_with model: @draft_translation, url: translation_proofreading_path(@translation.verse.id, resource_id: @resource.id), method: :put, html: { role: 'form', class: 'form', autocomplete: 'off', data: { controller: 'remote-form' } } do |form| %>
      <%= hidden_field_tag :resource_id, @resource.id %>
      <%= render 'shared/form_errors', object: @translation %>

      <div class="form-floating mb-3">
        <%= form.text_area :draft_text, class: "form-control #{lang}", autofocus: true, required: true %>
        <%= form.label :draft_text, 'Translation', required: true %>

        <div class="invalid-feedback">
          Translation can't be blank.
        </div>
      </div>

      <h3>Footnotes</h3>
      <%= form.fields_for :foot_notes, @draft_translation.foot_notes do |f_form| %>
        <div class="form-floating mb-3">
          <%= f_form.hidden_field :id %>
          <%= f_form.hidden_field :foot_note_id %>
          <%= f_form.text_area :draft_text, class: "form-control #{lang}", required: true %>
          <%= f_form.label :draft_text, "Footnote (#{f_form.object.foot_note_id})", required: true %>

          <div class="invalid-feedback">
            Footnote text can't be blank.
          </div>
        </div>
      <% end %>

      <div class="text-center mt-5">
        <%= link_to 'Cancel', translation_proofreading_path(@translation.verse.id, resource_id: @resource.id), class: 'btn btn-default' %>
        <%= form.submit 'Purpose changes', class: 'btn btn-success', data: { disable_with: 'Please wait...' } %>
      </div>
    <% end %>
  </div>
</div>

quranic-universal-library-main/app/views/translation_proofreadings/index.html.erb
<%= render 'tools/header',
           name: "Ayah translation",
           title: @presenter.page_title,
           # title: 'Ayah translation proofreading',
           key: 'ayah_translation'
%>

<div class="page-wrapper container-lg">
  <div class="page-section filters">
    <%= form_tag translation_proofreadings_path, method: :get do %>
      <div data-controller="chapter-verses-filter" class="d-flex tw-flex-wrap">
        <div class="form-group me-2">
          <%= select_tag :resource_id, options_from_collection_for_select(@ayah_translations, :id, :humanize, selected: @resource.id), include_blank: false, class: 'form-select tw-w-[85vw] sm:tw-w-[200px]', data: { placeholder: 'Select translation', controller: 'select2' } %>
          <p class="form-text">Select the translation</p>
        </div>

        <%= render 'shared/filters' %>

        <div class="form-group me-2">
          <%= text_field_tag :query, params[:query], class: 'form-control tw-w-[85vw] sm:tw-w-[200px] tw-border-gray-400 tw-rounded-[5px] tw-h-[38px]', placeholder: 'Search' %>
          <p class="form-text">Search translation content</p>
        </div>

        <div class="form-group">
          <%= submit_tag 'Filter', class: 'btn btn-primary', data: { disable_with: 'Please wait..' } %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="page-section mt-4">
    <h2><%= @resource.name %></h2>
    <div class="tools-table-overflow">
    <table class="table table-hover">
      <thead class="tw-sticky tw-top-0 tw-z-10 bg-white border-bottom">
      <tr>
        <th><%= sort_order_link 'Ayah key', :verse_key, resource_id: @resource.id %></th>
        <th>Footnotes</th>
        <th>Resource</th>
        <th>Text</th>
        <th>Actions</th>
      </tr>
      </thead>
      <tbody>
      <% @translations.each do |translation| %>
        <tr>
          <td scope="row"><%= translation.verse.verse_key %></td>
          <td>
            <%= translation.foot_notes.size %>
          </td>
          <td>
            <%= translation.resource_name %>
          </td>
          <td dir="<%= @resource.language&.direction %>">
            <%= safe_html translation.text %>
          </td>
          <td>
            <div class="d-flex gap-1">
              <%= link_to 'Edit', edit_translation_proofreading_path(translation.verse_id, resource_id: @resource.id), class: 'btn btn-info' %>
              <%= link_to 'Show', translation_proofreading_path(translation.verse_id, resource_id: @resource.id), class: 'btn btn-success' %>
            </div>
          </td>
        </tr>
      <% end %>
      <tr>
        <td colspan="4">
          <div class="d-flex align-items-center">
            <div class="me-4">
              <%= safe_html pagy_bootstrap_nav(@pagy) %>
            </div>

            <div>
              <%= safe_html pagy_info(@pagy) %>
            </div>
          </div>
        </td>
      </tr>
      </tbody>
    </table>
    </div>
  </div>
</div>

quranic-universal-library-main/app/views/translation_proofreadings/show.html.erb
<%
  actions = []
  more_action = []
  verse = @translation.verse
  view_type = params[:view_type].presence || 'ayah'

  if !translation_view_types.include?(view_type)
    view_type = 'ayah'
  end

  if @access
    actions << link_to('Edit', edit_translation_proofreading_path(verse.id, resource_id: @resource.id), class: 'btn btn-success')
  end

  more_action << link_to('Ayah view', translation_proofreading_path(verse.id, resource_id: @resource.id), class: 'dropdown-item')
  more_action << link_to('Page view', translation_proofreading_path(verse.id, resource_id: @resource.id, view_type: 'page'), class: 'dropdown-item')
  more_action << link_to('Page with arabic view', translation_proofreading_path(verse.id, resource_id: @resource.id, view_type: 'page_with_arabic'), class: 'dropdown-item')
  more_action << link_to('Proofreading view(With pdf)', translation_proofreading_path(verse.id, resource_id: @resource.id, view_type: 'page_with_pdf'), class: 'dropdown-item')

  actions << "<div class='dropdown'>
      <button class='btn btn-primary dropdown-toggle' type='button' data-bs-toggle='dropdown' aria-expanded='false'>
        Change view
      </button>
      <ul class='dropdown-menu text-dark'>
       #{more_action.map do |action|
    "<li>#{action}</li>"
  end.join('')
  }
    </ul>
    </div>"

  if view_type == 'ayah'
    previous_ayah = verse.previous_ayah
    next_ayah = verse.next_ayah
    if previous_ayah
      actions << link_to('Previous ayah', translation_proofreading_path(previous_ayah.id, resource_id: @resource.id), class: 'btn btn-dark')
    end
    if next_ayah
      actions << link_to('Next ayah', translation_proofreading_path(next_ayah.id, resource_id: @resource.id), class: 'btn btn-dark')
    end
  else
    page = verse.page_number

    if page > 1
      previous_ayah = Verse.where(page_number: page - 1).order('verse_index ASC').first
      actions << link_to('Previous page', translation_proofreading_path(previous_ayah.id, resource_id: @resource.id, view_type: params[:view_type]), class: 'btn btn-dark')
    end

    if page < 604
      next_ayah = Verse.where(page_number: page + 1).order('verse_index ASC').first

      actions << link_to('Next page', translation_proofreading_path(next_ayah.id, resource_id: @resource.id, view_type: params[:view_type]), class: 'btn btn-dark')
    end
  end

  actions << link_to('Back to filter', translation_proofreadings_path(resource_id: @resource.id), class: 'btn btn-info')
%>

<%= render 'tools/header',
           name: "Ayah translation",
           title: "#{@resource.name} - #{@translation.verse.verse_key}",
           key: 'ayah_translation',
           actions: actions
%>

<%= render 'shared/access_message' %>

<div class="page-wrapper container-lg">
  <div class="page-section">
    <%= render "#{view_type}_view", verse: verse %>
  </div>
</div>