quranic-universal-library-main/config/routes.rb
Rails.application.routes.draw do
  # Redirect old admin paths to new CMS paths
  get '/admin', to: redirect('/cms', status: 301)
  get '/admin/*path', to: redirect(status: 301) { |params, _req| "/cms/#{params[:path]}" }

  ActiveAdmin.routes(self)

  root to: 'landing#home'

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :chapters, only: [:index, :show] do
        member do
          get 'verses', to: 'verses#index', filter: 'by_chapter'
        end
      end

      namespace :audio do
        get 'surah_recitations', to: 'recitations#surah_recitations'
        get 'surah_recitations/:id', to: 'recitations#surah_recitation_detail'
        get 'surah_recitations/:id/wav_manifest', to: 'recitations#wav_manifest'

        get 'ayah_recitations', to: 'recitations#ayah_recitations'
        get 'ayah_recitations/:id', to: 'recitations#ayah_recitation_detail'

        get 'surah_segments/:recitation_id', to: 'segments#surah_segments'
        get 'ayah_segments/:recitation_id', to: 'segments#ayah_segments'
      end

      get '/verses/select2', to: 'verses#select2'
    end
  end

  get 'tools', to: 'community#tools', as: :tools
  get '/ayah-boundaries', to: 'community#ayah_boundaries', as: :ayah_boundaries
  get 'docs/:key', to: 'community#docs', as: :docs
  get 'tools/help/:key', to: 'community#tool_help', as: :tools_help
  get 'community/chars_info', as: :chars_info
  get 'svg', to: 'community#svg_optimizer'
  get 'credits', to: 'community#credits', as: :credits
  get 'faq', to: 'community#faq', as: :faq
  get '/compare_ayah', to: 'verses#compare', as: :compare_ayah
  
  get 'arabic_transliterations/:surah_number/export', to: "arabic_transliterations#render_surah"
  get 'foot_notes/:id', to: "foot_notes#show"

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  authenticated :user, ->(user) { user.is_super_admin? || user.is_admin? } do
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :tajweed_words, except: [:new, :destroy]
  get 'tajweed_rule/:rule', to: 'tajweed_words#rule_doc', as: :tajweed_rule

  resources :morphology_phrases do
    member do
      get :phrase_verses
    end
  end

  namespace :morphology do
    get 'roots/:id', to: 'roots#show', as: :root
    get 'lemmas/:id', to: 'lemmas#show', as: :lemma
    get 'stems/:id', to: 'stems#show', as: :stem
  end

  resources :user_projects, except: [:index, :destroy]
  resources :resources do
    get '/:token/download', action: 'download' , as: :download_file

    member do
      get :copyright
    end

    collection do
      get '/:type/:id', action: 'detail', as: :detail
      get '/:type/:id/related_resources', action: 'related_resources', as: :related
    end
  end

  resources :ayah_audio_files do
    member do
      get :segment_builder
      get :segments
      post :save_segments
    end
  end

  resources :surah_audio_files do
    member do
      get :segment_builder
      get :segments
      post :save_segments
    end

    collection do
      get :builder_help
    end
  end

  resources :mushaf_layouts, except: [:delete, :new] do
    member do
      put :save_page_mapping
      put :save_line_alignment
    end
  end

  resources :word_concordance_labels, only: [:show, :index] do
    member do
      get :word_detail
      get :segment_detail
      put :update_segment
    end
  end

  resources :learning_activities, only: [:show, :index]
  resources :arabic_transliterations, except: :delete
  resources :word_text_proofreadings, only: [:index, :show] do
    collection do
      get :compare_words
    end
  end
  resources :translation_proofreadings, except: :delete
  resources :tafsir_proofreadings, except: :delete
  resources :word_translations, except: :delete do
    member do
      match :group_info, via: [:get, :post]
    end
  end
  resources :surah_infos, except: :delete do
    member do
      get :history
      get :changes
    end
  end
  resources :translation_diffs, only: [:index, :show]

  namespace :exports do
    get :word
    get :ayah
    get :mushaf_page
    get :mushaf
  end

  namespace :segments do
    get '/', to: 'dashboard#show', as: :dashboard
    get '/failures', to: 'dashboard#failures', as: :failures
    get '/word_failures', to: 'dashboard#word_failures', as: :word_failures
    get '/word_failure_detail', to: 'dashboard#word_failure_detail', as: :word_failure_detail
    get '/detections', to: 'dashboard#detections', as: :detections
    get '/logs', to: 'dashboard#logs', as: :logs
    get '/reciters', to: 'dashboard#reciters', as: :reciters
    get '/reciters/:id', to: 'dashboard#reciter', as: :reciter
    get '/timeline', to: 'dashboard#timeline', as: :timeline
    get '/ayah_report', to: 'dashboard#ayah_report', as: :ayah_report
    get '/review_ayahs', to: 'dashboard#review_ayahs', as: :review_ayahs
    post '/reciters/:id/download', to: 'dashboard#download_reciter', as: :download_reciter
    match '/setup_db', to: 'dashboard#setup_db', via: [:get, :post], as: :setup_db
  end

  get '/ayah/:key', to: 'ayah#show', as: :ayah
  match '/404', to: 'application#not_found', via: :all
  #  match '*unmatched', to: 'application#not_found', via: :all
end

quranic-universal-library-main/app/controllers/landing_controller.rb
class LandingController < ApplicationController
  layout 'devise'

  def home
  end
end

quranic-universal-library-main/app/views/landing/_footer.html.erb
<footer class="tw-border-t">
  <%= render 'layouts/grid' do %>
    <div class="w-full tw-items-center tw-py-5 md:tw-py-8 md:tw-justify-between tw-flex tw-flex-col md:tw-flex-row tw-gap-3">
      <div class="tw-flex tw-flex-col tw-gap-3 tw-justify-between">
        <div class="tw-flex tw-gap-3 tw-items-center">
          <div class="qul-tag">
            <span>Quranic</span>
            <span>Universal</span>
            <span>Library</span>
          </div>
          <div class="tw-w-px tw-h-[30px] tw-bg-gray-400"></div>
          <div class="qul-tag">
            <svg width="39" height="32" viewBox="0 0 39 32" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path opacity="0.35" fill-rule="evenodd" clip-rule="evenodd" d="M30.9746 3.58175L29.4942 2.1367C29.3353 1.98164 29.3316 1.72737 29.4859 1.56776L30.8823 0.123023C31.0382 -0.0382324 31.2957 -0.0413724 31.4554 0.116033L32.9358 1.57465C33.0939 1.73045 33.0964 1.98474 32.9414 2.14362L31.545 3.57479C31.3894 3.73426 31.134 3.73737 30.9746 3.58175ZM34.7748 3.58033L33.2944 2.1353C33.1361 1.98079 33.1318 1.72763 33.2847 1.56782L34.6645 0.125922C34.8201 -0.0366866 35.0786 -0.0404899 35.2389 0.117472L36.7193 1.57607C36.8768 1.73131 36.88 1.98449 36.7263 2.14358L35.3466 3.57192C35.1913 3.73273 34.9348 3.73651 34.7748 3.58033ZM31.8262 4.67011H33.5014C36.9549 4.67011 38.7202 6.28344 38.7202 9.41976C38.7202 12.5561 36.9549 14.1694 33.5014 14.1694H31.8262C31.0679 14.1694 30.391 14.0916 29.7963 13.937H13.2443C12.6957 15.5523 11.2991 16.3571 9.07693 16.3571H4.4328C1.49478 16.3571 0 14.9503 0 12.1237V9.5101H2.19063V12.1237C2.19063 13.7112 3.1442 14.4598 4.94824 14.4727H8.56149C10.2569 14.4727 11.2012 13.8115 11.3088 12.4035V4.90236H13.4994V7.0901H13.5097V12.0526H27.1972C26.8049 11.3477 26.6074 10.469 26.6074 9.41976C26.6074 6.28344 28.3728 4.67011 31.8262 4.67011ZM32.2128 12.2979H33.1148C35.2926 12.285 36.4394 11.317 36.4394 9.41976C36.4394 7.50958 35.2926 6.54158 33.1148 6.54158H32.2128C30.0351 6.54158 28.8882 7.50958 28.8882 9.41976C28.8882 11.317 30.0351 12.285 32.2128 12.2979Z" fill="black"/>
              <path fill-rule="evenodd" clip-rule="evenodd" d="M6.94679 29.8564H5.25879C1.7789 29.8564 0 28.2301 0 25.1196C0 21.9704 1.7789 20.3571 5.25879 20.3571H6.94679C10.4267 20.3571 12.2056 21.9704 12.2056 25.1196C12.2056 27.1718 11.3746 28.6044 9.8164 29.3272L10.9331 31.16H8.47898L7.63498 29.8306C7.41424 29.8435 7.18052 29.8564 6.94679 29.8564ZM5.64833 27.9849H6.45338L5.28476 26.1522H7.92064L8.66077 27.3654L8.72569 27.4816C9.51775 27.0427 9.90729 26.2296 9.90729 25.1196C9.90729 23.1966 8.75166 22.2286 6.55725 22.2286H5.64833C3.45392 22.2286 2.29828 23.1966 2.29828 25.1196C2.29828 27.004 3.45392 27.972 5.64833 27.9849ZM27.6246 21.125V26.2103C27.6246 28.8819 25.9107 30.392 23.1579 30.392H18.2952C15.4905 30.392 13.8284 28.8819 13.8284 26.2103V21.125H16.1008V26.1586C16.1008 27.7849 16.776 28.4173 18.8795 28.4173H22.5866C24.6252 28.4173 25.3653 27.7849 25.3653 26.1586V21.125H27.6246ZM29.2155 21.1637V30.1984H38.7203V28.3269H31.4229V21.1637H29.2155Z" fill="black"/>
            </svg>
          </div>
        </div>
        <div class="md:tw-hidden">
          <a
          class="tw-text-gray-900 hover:tw-underline github-button"
          href="https://github.com/TarteelAI/quranic-universal-library"
          data-color-scheme="no-preference: light; light: light; dark: dark;"
          data-size="large"
          data-show-count="true"
          target="_blank"
          aria-label="Star QUL on Github"
          title="Star QUL on Github"
        >Star us</a>
        </div>
      </div>
      <div class="tw-flex tw-gap-5 tw-justify-start md:tw-justify-end">
        <%= link_to 'FAQ', faq_path, class: 'tw-text-gray-900 hover:tw-underline tw-w-[max-content]' %>
        <%= link_to 'Credits', credits_path, class: 'tw-text-gray-900 hover:tw-underline tw-w-[max-content]' %>
        <%= link_to 'Terms of use', 'https://www.tarteel.ai/terms', class: 'tw-text-gray-900 hover:tw-underline tw-w-[max-content]', target: '_blank' %>
        <%= link_to 'Privacy Policy', 'https://www.tarteel.ai/privacy', class: 'tw-text-gray-900 hover:tw-underline tw-w-[max-content]', target: '_blank' %>
        <div class="tw-hidden md:tw-block">
          <a
          class="tw-text-gray-900 hover:tw-underline github-button"
          href="https://github.com/TarteelAI/quranic-universal-library"
          data-color-scheme="no-preference: light; light: light; dark: dark;"
          data-size="large"
          data-show-count="true"
          target="_blank"
          aria-label="Star QUL on Github"
          title="Star QUL on Github"
        >Star us</a>
        </div>
        <script async defer src="https://buttons.github.io/buttons.js"></script>
      </div>
    </div>
  <% end %>
</footer>

quranic-universal-library-main/app/views/landing/_overview.html.erb
<%= render 'layouts/grid' do %>
  <div class="tw-py-4 md:tw-py-8">
    <p class="tw-font-semibold tw-text-gray-900">OVERVIEW</p>
    <div class="tw-flex tw-flex-col md:tw-flex-row md:tw-gap-8 lg:tw-gap-16 tw-mt-3">
      <!-- Left column -->
      <div class="tw-max-w-prose tw-text-pretty">
        <h2 class="tw-text-3xl tw-font-normal tw-text-gray-900 tw-max-w-[10ch] md:tw-text-5xl">
          <span class="tw-font-sarina">Reigniting</span> <br/>
          the Islamic Golden Age.
        </h2>
        <div class="tw-mt-4">
          <p class="tw-text-lg md:tw-text-xl tw-font-thin">
            <span class="tw-font-semibold">QUL</span> <span class="tw-font-medium">— Quranic Universal Library,</span> provides a comprehensive, centralized hub of essential digital Quran resources, allowing you to go from idea to impact much faster.
          </p>
          <%= link_to 'GET STARTED', resources_path, class: 'tw-hidden md:tw-inline-block tw-mt-4 tw-px-8 tw-py-3 tw-bg-gray-900 tw-text-white tw-rounded-full tw-text-sm tw-font-semibold hover:tw-bg-gray-800 hover:tw-text-white tw-transition-colors', id: 'get-started' %>
        </div>
      </div>
      <!-- Right column -->
      <div class="tw-max-w-prose tw-mt-4 tw-text-gray-600 tw-text-pretty">
        <p class="tw-text-lg md:tw-text-2xl md:tw-font-thin md:tw-text-black">
          Islamic projects are built upon the same universal resources: the Quran, its translations, its tafsir, recitations of it, and related content and data. 
        </p>
        <p class="tw-text-lg tw-mt-4">
          To save you time and effort when it comes to sourcing, formatting, and auditing all the Quranic resources you need for your project, we've curated and open-sourced them. We've also included the tools necessary to interact with and explore them.
        </p>
        <p class="tw-text-lg tw-mt-4">
          QUL is primarily geared towards other Muslim developers. To contribute, visit the QUL repo on <a href="https://github.com/TarteelAI/quranic-universal-library" class="tw-text-gray-900 tw-underline hover:tw-text-gray-700">Github</a>.
          Special thanks to <%= link_to 'all those whose contributions made this project possible', credits_path, class: "tw-text-gray-900 tw-underline hover:tw-text-gray-700" %>.
        </p>
      </div>
    </div>
    <!-- Mobile 'GET STARTED' button -->
    <div class="tw-w-full md:tw-hidden tw-mt-7">
      <%= link_to 'GET STARTED', resources_path, class: 'tw-block tw-w-full tw-px-8 tw-py-4 tw-bg-gray-900 tw-text-white tw-text-center tw-rounded-full tw-text-sm tw-font-semibold hover:tw-bg-gray-800 tw-transition-colors hover:tw-text-white', id: 'get-started' %>
    </div>
  </div>
<% end %>

quranic-universal-library-main/app/views/landing/_resources.html.erb
<div class="sidescroll-container">
  <h2 class="tw-text-3xl md:tw-text-5xl tw-text-white tw-font-title">Developer Resources</h2>
</div>
<div class="tw-mt-10">
  <%= render 'card/card_sidescrolling_container' do %>
    <% featured_developer_resources.each do |card| %>
      <%= render 'card/card-container', card: card do %>
        <%= render 'card/card_content', card: card, show_stats: true %>
      <% end %>
    <% end %>
  <% end %>
</div>
<div class="sidescroll-container">
  <p class="tw-mt-10">
    <%= link_to 'VIEW ALL DEVELOPER RESOURCES', resources_path, class: 'tw-text-white tw-opacity-70 tw-font-semibold hover:tw-opacity-100 hover:tw-text-white tw-transition-opacity tw-duration-300' %>
  </p>
</div>

quranic-universal-library-main/app/views/landing/_spline.html.erb
<script type="module" src="https://unpkg.com/@splinetool/viewer/build/spline-viewer.js"></script>
<div class="tw-w-full tw-h-full tw-flex tw-justify-center tw-items-center">
  <spline-viewer
    url="https://static-cdn.tarteel.ai/qul/spline/scene.splinecode"
    width="800"
    height="800"
    class="tw-scale-75 md:tw-scale-100"
  ></spline-viewer>
</div>

quranic-universal-library-main/app/views/landing/_tools.html.erb
<%
  patterns = (1..10).to_a
%>
<div class="sidescroll-container">
  <h2 class="tw-text-3xl md:tw-text-5xl tw-text-white tw-font-title">Developer Tools</h2>
</div>
<div class="tw-mt-10">
  <%= render 'card/card_sidescrolling_container' do %>
    <% featured_developer_tools.each do |card| %>
      <%= render 'card/card-container', card: card, patterns: patterns do %>
        <%= render 'card/card_content', card: card, show_learn_more: true, show_tags: true, tool: true %>
      <% end %>
    <% end %>
  <% end %>
</div>
<div class="sidescroll-container">
  <p class="tw-mt-10">
    <%= link_to 'VIEW ALL DEVELOPER TOOLS', tools_path, class: 'tw-text-white tw-opacity-70 tw-font-semibold hover:tw-opacity-100 hover:tw-text-white tw-transition-opacity tw-duration-300' %>
  </p>
</div>

quranic-universal-library-main/app/views/landing/home.html.erb
<div class="tw-flex tw-justify-center tw-flex-col tw-items-center tw-px-4 lg:tw-px-8 tw-mt-[60px] md:tw-mt-[75px]">
  <div class="tw-bg-black tw-rounded-3xl tw-text-white tw-w-full tw-max-w-[1600px] tw-relative tw-overflow-hidden tw-z-10">
    <div class="tw-grid tw-grid-cols-1 lg:tw-grid-cols-2 tw-min-h-[500px] md:tw-min-h-[600px]">
      <div class="tw-absolute tw-h-full tw-w-full lg:tw-w-1/2 tw-left-0">
        <div class="lg:tw-hidden tw-absolute tw-bottom-0 tw-left-0 tw-right-0 tw-bg-gradient-to-t tw-from-black/70 tw-to-transparent tw-z-10 tw-h-2/3 md:tw-h-full"></div>
        <%= render 'landing/spline' %>
      </div>
      <div class="tw-hidden lg:tw-block tw-col-span-1"><!-- Empty column for spline background --></div>
      <%= render 'landing/hero' %>
    </div>
  </div>
</div>

<%= render 'landing/overview' %>

<div class="tw-bg-black tw-text-white tw-py-10 md:tw-py-16 tw-mt-4">
  <%= render 'landing/resources' %>
</div>

<div class="tw-text-white tw-py-10 md:tw-py-16 tw-bg-[#404040]">
  <%= render 'landing/tools' %>
</div>